type IconProps = React.HTMLAttributes<SVGElement>;

/**
 * Halftone half-circle "dome" of dots — the Mesynx AI mark.
 * Matches the icon pack (chrome-extension/icons). Rendered in `currentColor`
 * with per-dot opacity falling off toward the edges for a halftone depth
 * effect. Designed on a 0–32 viewBox so it can sit alongside the wordmark.
 */
const DotDome = () => (
    <g>
        <circle
            cx="10.55"
            cy="9.7"
            r="1.02"
            fill="currentColor"
            fillOpacity={0.54}
        />
        <circle
            cx="13.4"
            cy="9.7"
            r="1.02"
            fill="currentColor"
            fillOpacity={0.57}
        />
        <circle
            cx="16.25"
            cy="9.7"
            r="1.02"
            fill="currentColor"
            fillOpacity={0.58}
        />
        <circle
            cx="19.1"
            cy="9.7"
            r="1.02"
            fill="currentColor"
            fillOpacity={0.56}
        />
        <circle
            cx="21.95"
            cy="9.7"
            r="1.02"
            fill="currentColor"
            fillOpacity={0.53}
        />
        <circle
            cx="7.7"
            cy="12.55"
            r="1.02"
            fill="currentColor"
            fillOpacity={0.56}
        />
        <circle
            cx="10.55"
            cy="12.55"
            r="1.02"
            fill="currentColor"
            fillOpacity={0.63}
        />
        <circle
            cx="13.4"
            cy="12.55"
            r="1.02"
            fill="currentColor"
            fillOpacity={0.67}
        />
        <circle
            cx="16.25"
            cy="12.55"
            r="1.02"
            fill="currentColor"
            fillOpacity={0.68}
        />
        <circle
            cx="19.1"
            cy="12.55"
            r="1.02"
            fill="currentColor"
            fillOpacity={0.66}
        />
        <circle
            cx="21.95"
            cy="12.55"
            r="1.02"
            fill="currentColor"
            fillOpacity={0.62}
        />
        <circle
            cx="24.8"
            cy="12.55"
            r="1.02"
            fill="currentColor"
            fillOpacity={0.55}
        />
        <circle
            cx="4.85"
            cy="15.4"
            r="1.02"
            fill="currentColor"
            fillOpacity={0.55}
        />
        <circle
            cx="7.7"
            cy="15.4"
            r="1.02"
            fill="currentColor"
            fillOpacity={0.63}
        />
        <circle
            cx="10.55"
            cy="15.4"
            r="1.02"
            fill="currentColor"
            fillOpacity={0.71}
        />
        <circle
            cx="13.4"
            cy="15.4"
            r="1.02"
            fill="currentColor"
            fillOpacity={0.76}
        />
        <circle
            cx="16.25"
            cy="15.4"
            r="1.02"
            fill="currentColor"
            fillOpacity={0.78}
        />
        <circle
            cx="19.1"
            cy="15.4"
            r="1.02"
            fill="currentColor"
            fillOpacity={0.76}
        />
        <circle
            cx="21.95"
            cy="15.4"
            r="1.02"
            fill="currentColor"
            fillOpacity={0.7}
        />
        <circle
            cx="24.8"
            cy="15.4"
            r="1.02"
            fill="currentColor"
            fillOpacity={0.62}
        />
        <circle
            cx="27.65"
            cy="15.4"
            r="1.02"
            fill="currentColor"
            fillOpacity={0.53}
        />
        <circle
            cx="4.85"
            cy="18.25"
            r="1.02"
            fill="currentColor"
            fillOpacity={0.59}
        />
        <circle
            cx="7.7"
            cy="18.25"
            r="1.02"
            fill="currentColor"
            fillOpacity={0.68}
        />
        <circle
            cx="10.55"
            cy="18.25"
            r="1.02"
            fill="currentColor"
            fillOpacity={0.77}
        />
        <circle
            cx="13.4"
            cy="18.25"
            r="1.02"
            fill="currentColor"
            fillOpacity={0.85}
        />
        <circle
            cx="16.25"
            cy="18.25"
            r="1.02"
            fill="currentColor"
            fillOpacity={0.88}
        />
        <circle
            cx="19.1"
            cy="18.25"
            r="1.02"
            fill="currentColor"
            fillOpacity={0.84}
        />
        <circle
            cx="21.95"
            cy="18.25"
            r="1.02"
            fill="currentColor"
            fillOpacity={0.76}
        />
        <circle
            cx="24.8"
            cy="18.25"
            r="1.02"
            fill="currentColor"
            fillOpacity={0.66}
        />
        <circle
            cx="27.65"
            cy="18.25"
            r="1.02"
            fill="currentColor"
            fillOpacity={0.57}
        />
        <circle
            cx="4.85"
            cy="21.1"
            r="1.02"
            fill="currentColor"
            fillOpacity={0.6}
        />
        <circle
            cx="7.7"
            cy="21.1"
            r="1.02"
            fill="currentColor"
            fillOpacity={0.7}
        />
        <circle
            cx="10.55"
            cy="21.1"
            r="1.02"
            fill="currentColor"
            fillOpacity={0.8}
        />
        <circle
            cx="13.4"
            cy="21.1"
            r="1.02"
            fill="currentColor"
            fillOpacity={0.91}
        />
        <circle
            cx="16.25"
            cy="21.1"
            r="1.02"
            fill="currentColor"
            fillOpacity={0.98}
        />
        <circle
            cx="19.1"
            cy="21.1"
            r="1.02"
            fill="currentColor"
            fillOpacity={0.89}
        />
        <circle
            cx="21.95"
            cy="21.1"
            r="1.02"
            fill="currentColor"
            fillOpacity={0.79}
        />
        <circle
            cx="24.8"
            cy="21.1"
            r="1.02"
            fill="currentColor"
            fillOpacity={0.69}
        />
        <circle
            cx="27.65"
            cy="21.1"
            r="1.02"
            fill="currentColor"
            fillOpacity={0.58}
        />
        <circle
            cx="16"
            cy="23.1"
            r="1.02"
            fill="currentColor"
            fillOpacity={0.85}
        />
        <circle
            cx="17.6"
            cy="24.6"
            r="1.02"
            fill="currentColor"
            fillOpacity={0.85}
        />
        <circle
            cx="19.2"
            cy="26.1"
            r="1.02"
            fill="currentColor"
            fillOpacity={0.85}
        />
    </g>
);

export const Logo = ({ className, ...props }: IconProps) => {
    return (
        <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 32 32"
            width="32"
            height="32"
            {...props}
            fill="none"
            className={className}
            aria-label="Mesynx AI Logo"
            aria-hidden="true"
        >
            <DotDome />
        </svg>
    );
};

export const LogoWordmark = ({ className, ...props }: IconProps) => {
    return (
        <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 150 32"
            width="150"
            height="32"
            {...props}
            fill="none"
            className={className}
            aria-label="Mesynx AI Wordmark"
            aria-hidden="true"
        >
            {/* Logo mark — halftone dome */}
            <DotDome />
            {/* Wordmark text */}
            <text
                x="40"
                y="24"
                fill="currentColor"
                fontFamily="system-ui, -apple-system, 'Segoe UI', sans-serif"
                fontSize="20"
                fontWeight="700"
                letterSpacing="-0.02em"
            >
                Mesynx AI
            </text>
        </svg>
    );
};
